/**
 * Validation for LLM-authored KBF probe candidates.
 *
 * The CLI's probe author asks an upstream frontier model for candidate KBF
 * probes as a JSON array. Nothing an LLM emits is trusted: every candidate is
 * revalidated field-by-field here (manual checks — this package stays
 * dependency-free, no zod), volatile time-sensitive facts are rejected, and
 * the probe `id` is GENERATED from the content rather than taken from the
 * model. Certification (reference-model consistency + holdout self-error)
 * happens downstream in the CLI; this module only guards shape and content.
 *
 * No LLM calls happen here — pure validation.
 */

import { canonicalJsonStringify, sha256Hex } from './canonical-json.js';
import type { KbfProbe } from './types.js';

// ---------------------------------------------------------------------------
// Banned volatile patterns
// ---------------------------------------------------------------------------

/**
 * Case-insensitive patterns for time-sensitive facts that make bad probes:
 * their true answers drift, so fingerprint disagreement would reflect data
 * freshness rather than model identity. Deliberately conservative — a false
 * positive costs one candidate out of an oversampled batch, a false negative
 * poisons an audit. Word-bounded so e.g. "Stockholm" does not trip "stock".
 */
export const BANNED_VOLATILE_PATTERNS: readonly RegExp[] = [
  /\bpopulation\b/i,
  /\bprices?\b/i,
  /\bcurrent(?:ly)?\b/i,
  /\blatest\b/i,
  /\btoday\b/i,
  /\bthis\s+year\b/i,
  /\bas\s+of\b/i,
  /\brecord\s+high\b/i,
  /\bnewest\b/i,
  /\bstocks?\b/i,
  /\bmarket\s+cap(?:italization)?\b/i,
];

// ---------------------------------------------------------------------------
// Probe id generation
// ---------------------------------------------------------------------------

/** Inclusive template length bounds for LLM-authored probes. */
export const LLM_TEMPLATE_MIN_LENGTH = 20;
export const LLM_TEMPLATE_MAX_LENGTH = 500;

function slugifyDomain(domain: string): string {
  return domain
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Content-derived probe id for an LLM-authored candidate:
 * `llm:<domain-slug>:<first 12 hex of sha256(canonical JSON of template)>`.
 * Generated by the validator — never taken from the LLM — so an upstream
 * model cannot mint colliding or misleading ids. Same (domain, template)
 * always yields the same id, which makes rotation-log dedupe content-based.
 */
export function computeLlmProbeId(domain: string, template: string): string {
  const digest = sha256Hex(canonicalJsonStringify(template)).slice(0, 12);
  return `llm:${slugifyDomain(domain)}:${digest}`;
}

// ---------------------------------------------------------------------------
// Single-candidate validation
// ---------------------------------------------------------------------------

export type CandidateProbeResult =
  | { ok: true; probe: KbfProbe }
  | { ok: false; reason: string };

function fail(reason: string): CandidateProbeResult {
  return { ok: false, reason };
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === 'number' && Number.isFinite(value);
}

/**
 * Validate one parsed LLM candidate. On success returns a freshly constructed
 * `KbfProbe` containing ONLY the validated fields (any extra fields the LLM
 * attached — including a self-supplied `id` — are dropped as untrusted).
 */
export function validateCandidateProbe(raw: unknown): CandidateProbeResult {
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
    return fail('candidate must be a plain object');
  }
  const obj = raw as Record<string, unknown>;

  const name = obj['name'];
  if (typeof name !== 'string' || name.trim() === '') {
    return fail('name must be a non-empty string');
  }

  const domain = obj['domain'];
  if (typeof domain !== 'string' || domain.trim() === '') {
    return fail('domain must be a non-empty string');
  }
  if (slugifyDomain(domain) === '') {
    return fail('domain must contain at least one alphanumeric character');
  }

  const template = obj['template'];
  if (typeof template !== 'string') {
    return fail('template must be a string');
  }
  if (!template.includes('___')) {
    return fail('template must contain the ___ cloze marker');
  }
  if (
    template.length < LLM_TEMPLATE_MIN_LENGTH ||
    template.length > LLM_TEMPLATE_MAX_LENGTH
  ) {
    return fail(
      `template length must be ${LLM_TEMPLATE_MIN_LENGTH}..${LLM_TEMPLATE_MAX_LENGTH} characters`,
    );
  }
  for (const pattern of BANNED_VOLATILE_PATTERNS) {
    if (pattern.test(template)) {
      return fail(`template matches banned volatile pattern /${pattern.source}/i`);
    }
  }

  const consensus = obj['consensus'];
  if (!isFiniteNumber(consensus)) {
    return fail('consensus must be a finite number');
  }

  const range = obj['range'];
  if (!Array.isArray(range) || range.length !== 2) {
    return fail('range must be a [lo, hi] pair');
  }
  const [lo, hi] = range as [unknown, unknown];
  if (!isFiniteNumber(lo) || !isFiniteNumber(hi)) {
    return fail('range bounds must be finite numbers');
  }
  if (!(lo < hi)) {
    return fail('range lo must be strictly less than hi');
  }
  if (consensus < lo || consensus > hi) {
    return fail('consensus must lie within range');
  }

  const tolerance = obj['tolerance'];
  if (typeof tolerance !== 'object' || tolerance === null || Array.isArray(tolerance)) {
    return fail('tolerance must be an object');
  }
  const { mode, value } = tolerance as Record<string, unknown>;
  if (mode !== 'absolute' && mode !== 'relative') {
    return fail('tolerance.mode must be "absolute" or "relative"');
  }
  if (!isFiniteNumber(value) || value < 0) {
    return fail('tolerance.value must be a finite number >= 0');
  }
  if (mode === 'relative' && value > 1) {
    return fail('relative tolerance.value must be <= 1');
  }

  const probe: KbfProbe = {
    id: computeLlmProbeId(domain, template),
    name,
    domain,
    template,
    consensus,
    range: [lo, hi],
    tolerance: { mode, value },
  };
  return { ok: true, probe };
}

// ---------------------------------------------------------------------------
// Batch validation
// ---------------------------------------------------------------------------

export interface CandidateProbesResult {
  probes: KbfProbe[];
  rejected: Array<{ index: number; reason: string }>;
}

/**
 * Validate a parsed LLM candidate array. Invalid entries are collected in
 * `rejected` with their array index; duplicate content (same generated id)
 * within the batch is rejected too, so `probes` never contains id collisions.
 * A non-array payload yields a single rejection with `index: -1` (the whole
 * payload, no element to point at).
 */
export function validateCandidateProbes(raw: unknown): CandidateProbesResult {
  if (!Array.isArray(raw)) {
    return {
      probes: [],
      rejected: [{ index: -1, reason: 'candidate payload must be a JSON array' }],
    };
  }
  const probes: KbfProbe[] = [];
  const rejected: Array<{ index: number; reason: string }> = [];
  const seenIds = new Set<string>();
  for (let i = 0; i < raw.length; i++) {
    const result = validateCandidateProbe(raw[i]);
    if (!result.ok) {
      rejected.push({ index: i, reason: result.reason });
      continue;
    }
    if (seenIds.has(result.probe.id)) {
      rejected.push({ index: i, reason: `duplicate probe id ${result.probe.id}` });
      continue;
    }
    seenIds.add(result.probe.id);
    probes.push(result.probe);
  }
  return { probes, rejected };
}
