import { randomUUID } from 'node:crypto'
import type { AntseedNode, PeerInfo } from '@antseed/node'
import type { ProbeSet } from '@antseed/fingerprints'
import { buildStealthChatRequests, extractAnswersFreeText } from '@antseed/fingerprints'

const RESPONSE_AUTH_POLL_INTERVAL_MS = 500
const RESPONSE_AUTH_POLL_TIMEOUT_MS = 35_000

export interface SellerProbeRun {
  peerId: string
  agentId: number | undefined
  /** Parsed numeric answers, position-aligned with probeSet.probes. */
  answers: Array<number | null>
  requestIds: string[]
  /** Verified ResponseAuth hashes per request, aligned with requestIds (null = missing/unverified). */
  responseAuths: Array<{ requestHash: string; responseHash: string; signature: string } | null>
  /** True when every probe request produced a verified ResponseAuth. */
  fullyAuthenticated: boolean
  errors: string[]
}

function extractCompletionText(body: Uint8Array): string | null {
  try {
    const parsed = JSON.parse(new TextDecoder().decode(body)) as {
      choices?: Array<{ message?: { content?: unknown }; text?: unknown }>
      content?: Array<{ type?: string; text?: unknown }>
    }
    const chatContent = parsed.choices?.[0]?.message?.content
    if (typeof chatContent === 'string') return chatContent
    const text = parsed.choices?.[0]?.text
    if (typeof text === 'string') return text
    const anthropicText = parsed.content?.find((block) => block?.type === 'text')?.text
    if (typeof anthropicText === 'string') return anthropicText
    return null
  } catch {
    return null
  }
}

async function waitForResponseAuth(
  node: AntseedNode,
  requestId: string,
): Promise<{ requestHash: string; responseHash: string; signature: string } | null> {
  const deadline = Date.now() + RESPONSE_AUTH_POLL_TIMEOUT_MS
  for (;;) {
    const record = node.getResponseAuth(requestId)
    if (record) {
      if (!record.verified) return null
      return {
        requestHash: record.requestHash,
        responseHash: record.responseHash,
        signature: record.signature,
      }
    }
    if (Date.now() >= deadline) return null
    await new Promise((resolve) => setTimeout(resolve, RESPONSE_AUTH_POLL_INTERVAL_MS))
  }
}

/**
 * Probe one seller with the full probe set. Requests are generated by the
 * stealth engine so they read like organic user chat rather than a
 * recognizable test battery — a cheating seller cannot cheaply classify probe
 * traffic and route only it to the real model. Payment negotiation
 * (402 → ReserveAuth/SpendingAuth) is handled by the node's buyer path.
 *
 * `maxProbesPerRequest` trades stealth (fewer probes per message = more
 * organic) against cost (more requests = more per-request minimum fees).
 */
export async function probeSeller(
  node: AntseedNode,
  peer: PeerInfo,
  service: string,
  probeSet: ProbeSet,
  maxProbesPerRequest = 3,
): Promise<SellerProbeRun> {
  // Answers aligned to the full probe set; stealth plans cover disjoint
  // subsets, so we scatter each plan's extracted answers back by index.
  const answers: Array<number | null> = new Array(probeSet.probes.length).fill(null)
  const requestIds: string[] = []
  const responseAuths: SellerProbeRun['responseAuths'] = []
  const errors: string[] = []

  const plans = buildStealthChatRequests(service, probeSet, { maxProbesPerRequest })

  for (const plan of plans) {
    const requestId = randomUUID()
    const req = {
      requestId,
      method: 'POST',
      path: '/v1/chat/completions',
      headers: { 'content-type': 'application/json' },
      body: new TextEncoder().encode(JSON.stringify(plan.body)),
    }

    requestIds.push(requestId)
    try {
      const response = await node.sendRequest(peer, req)
      if (response.statusCode !== 200) {
        errors.push(`request ${requestId.slice(0, 8)}: HTTP ${response.statusCode}`)
        responseAuths.push(null)
        continue
      }
      const text = extractCompletionText(response.body)
      if (text === null) {
        errors.push(`request ${requestId.slice(0, 8)}: unparseable completion body`)
      } else {
        const planAnswers = extractAnswersFreeText(text, plan.probes)
        plan.probeIndices.forEach((probeIndex, i) => {
          answers[probeIndex] = planAnswers[i] ?? null
        })
      }
      responseAuths.push(await waitForResponseAuth(node, requestId))
    } catch (err) {
      errors.push(`request ${requestId.slice(0, 8)}: ${(err as Error).message}`)
      responseAuths.push(null)
    }
  }

  return {
    peerId: peer.peerId,
    agentId: peer.onChainAgentId,
    answers,
    requestIds,
    responseAuths,
    fullyAuthenticated: responseAuths.length > 0 && responseAuths.every((auth) => auth !== null),
    errors,
  }
}
